export const especializacion = ["Mago", "Guerrero", "Arquero", "Picaro"]

export const localizaciones = ["Comarca", "BosqueTroll", "CuevaTroll", "Llanuras","Rivendell","Montañas","Guarida de Gollum","Batalla Final"]

export const tiposelfo = ["Medio Elfo","Elfo del Bosque","Elfo Noldor"]

export const fondos = {
  fondo1: "imagenes/esc1.png",    //////escena de la casa bilbo
  fondo2: "imagenes/esc2.png",    //////escena de los troles
  fondo3: "imagenes/esc3.png",    //////escena de la cueva troll
  fondo4: "imagenes/esc4.png",    //////escena pelea con orcos
  fondo5: "imagenes/esc5.png",    //////escena rivendel
  fondo6: "imagenes/esc6.png",    //////escena elemental
  fondo7: "imagenes/esc7.png",    ///////escena gollum
  fondo8: "imagenes/esc8.png",    ///////azog
  fondo9: "imagenes/youdied.png",   //////muerte del pnj
  fondo10: "imagenes/continuara.png",   //////to be continued
};

export const dialogos = {
    escena1:"Bilbo Bolsón vive una vida tranquila y cómoda en Bolsón Cerrado, una región pacífica de la Comarca. Su vida se ve completamente alterada cuando Gandalf, el mago, y un grupo de enanos liderados por Thorin Escudo de Roble, llegan a su puerta. Estos personajes buscan a alguien hábil y valiente para unirse a su búsqueda de recuperar el tesoro guardado por el dragón Smaug en la Montaña Solitaria. <br>",
    escena11:"Has decidido quedarte en la comodidad de tu casa. La cama está muy calentita y es hora de la tercera merienda. Gandalf marcha, pero hay un creciente sentimiento de arrepentimiento, por mucho que te guste tu humilde hogar, que se hace cada vez más grande en tu pecho. El té te consuela, pero... Se acaba tu partida.<br>",
    escena12:"Has decidido unirte a la compañia de los enanos. Un escalofrio recorrer tu espalda, y ni siquiera sabes por que has dicho que si, pero sabes que no había ninguna otra respuesta correcta. Gandalf te mira con orgullo y una picaresca sonrisa decora las comisuras de sus labios, casi ocultos bajo su majestuosa barba. Thorin te mira con recelo, pero el resto de enanos están contentos con tu afirmativa. Lo que tienes por seguro, es que te espera por delante una gran aventura.<br>",
    escena2:"En lo profundo del frondoso Bosque Negro, Bilbo Bolsón junto a la compañía de enanos se aventuró audazmente, desafiando las sombras que se cerraban a su alrededor. Sus pasos resonaban en la penumbra, mientras el murmullo de las hojas y el susurro de las criaturas ocultas creaban una sinfonía misteriosa.<br> De repente, emergiendo de la espesura, el grupo se encontró frente a tres figuras gigantes e imponentes: Tom, Berto y Guille, conocidos como los tres Troles. Sus cuerpos grotescos y amenazadores proyectaban sombras danzantes, y sus ojos brillaban con malicia. Un escalofrío recorrió la columna vertebral de Bilbo mientras se preguntaba qué intriga acechaba detrás de esas miradas vacías.<br> Los Troles, con sus voces estridentes y gruñidos guturales, rompieron el silencio del bosque: En un abrir y cerrar los ojos, atraparon a todos los enanos. Escondido entre las sombras, sopesas tu próxima movida. ¿Deslizarte como una sombra inadvertida o enfrentar a estos colosos? Sopesas la decisión mientras observas la escena.<br>",
    escena21:"Sientes que tu cuerpo se llena de valor aunque tus peludos pies tiemblen con tan solo pensar en que has de enfrentarte a los tres colosos que amenazan con devorar a tus amigos. Te agachas, te haces con una rama de ciprés en la diestra y una piedra en la izquierda. Saltas de entre los arbustos, y decides lanzar una de las piedras a uno de los troles. Fallas, y Guille te da con el dedo, como si fueses una canica. <b>Pierdes 1 punto de vida</b>, pero escuchas a tu salvador: Gandalf, que había desaparecido durante el camino, rompe la piedra que había sobre la colina y fortuitos rayos de luz alcanzan a los troles. Éstos se convierten en piedra, y liberas a los enanos.<br>",
    escena22:"Desde luego, abusar de la escasa inteligencia de los troles es tu mejor baza. Saltas de entre los arbustos y empiezas a atosigar a los tres toles con enrevesadas preguntas. ¿De qué color es el sol? ¿Cuál de los tres es más listo? ¿Y más guapo? Comienzan a discutir entre los tres, hasta que escuchas a tu salvador: Gandalf, que había desaparecido durante el camino, rompe la piedra que había sobre la colina y fortuitos rayos de luz alcanzan a los troles. Éstos se convierten en piedra, y liberas a los enanos.<br>",
    escena3:"Después de tu <b>victoria épica</b> contra los troles, avanzas con paso firme junto a los enanos y Gandalf, adentrándote en los recovecos del bosque hasta tropezar con la oscura guarida de estas criaturas. El hedor a descomposición se cierne en el aire, mientras el suelo está sembrado de carcasas, huesos y polvo, testimonios silentes de las brutales festines de los troles. No obstante, entre las sombras, descubres tesoros que, aunque carecían de valor para los trolles, despiertan en ti una codicia insaciable. Entre montones de objetos despreciados, tu mirada ávida se posa en varias espadas relucientes, cuyas hojas parecen susurrar antiguas hazañas. Thorin, a tu lado, comparte tu fascinación, y juntos, os detenéis frente a dos de estas armas en particular. Su belleza y presencia imponente no pasan desapercibidas, y sabes que estas espadas no solo son objetos inanimados, sino reliquias que encierran historias por descubrir. La elección de empuñar estas espadas no solo marcará un cambio en tu destino, sino que también te sumergirá más profundamente en la trama de esta inolvidable odisea.<br>",
    escena31:"Sabes que es mala idea. Intentáis plantarles cara. <b>Pierdes una vida<b/>. Tienes dos opciones: <b>A: Seguir plantándoles cara</b>, o <b>B: Darles la espalda y tratar de huir.<b><br>",
    escena32:"Logras poner tus ideas en orden incluso por encima de ese incesable tembleque de piernas que te invade. Thorin, junto a Dwalin, salen ya armas en mano. Pero logras hacerles entrar en razon: Podéis correr, buscar un refugio o ayuda. Así lo hacéis, y siguiendo tu consejo, corriendo hasta que os duele el cuerpo y sorteando piedras y árboles para escapar de los fauces huargos, escucháis un cuerno élfico: Antes de que os deis cuenta, una patrulla de elfos de Rivendell acude en vuestro rescate y erradica sin dificultad alguna a la emboscada de orcos.<br>",
    escena4:"Has sido escoltado por los elfos hasta llegar a la capital élfica de Rivendell. El paisaje te deja sin aliento, todo parece hecho no por manos, sino por magia. Las plantas y follaje se hacen uno con la infraestructura de aquella majestuosa ciudad entre bosques y montañas, pero notas como Thorin y los demás enanos tienen cara de querer irse de ahí cuanto antes, incluso cuando es el lugar más hermoso que hayas visto en tu vida, ¡incluso para estándares hobbit! ¿Plantas decorativas? Elfos... O espera, ¿son elfas? Es dificil distinguirlos. Elfos que tocan suave música, y falsa pomposidad que nada vale para los enanos. Elrond y Galadriel os reciben, y nada tardan en entablar conversa con Gandalf.<br>",
    escena41:"A regañadientes, convences a los enanos para que acepten formar parte del banquete, por muy mala pinta que tenga tanto vegetal. Al menos tienen vino, y aunque no sepa tan bien como la bebida de los dioses enanos: La cerveza, el ambiente se alegra lo suficiente como para que un desfile enano desordene la mesa al usarla como escenario para sus bailes y cánticos. Los elfos se quedan perplejos, pero al menos logrs <b>guardar un pan de lembas en tu inventario</b> cuando nadie miraba. Lo más seguro es que nadie se hubiese opuesto, pero... ¡Está en tu naturaleza de hobbit moverte sin que nadie se percate! Además, tú no le haces feos a los vegetales élficos, así que tras lograr colarte un par de frutas en la boca cual ardilla, <b>ganas +1 punto de vida</b><br>",
    escena42:"Los enanos están gruñendo demasiado incluso cuando se les ha invitado a formar parte de un banquete. Mucho verde, y demasiadas cosas no comestibles. Ni siquiera hay cerveza, y la compañía quiere irse cuanto antes del lugar. Gandalf sigue hablando con Galadriel y Elrond, así que decides seguirle el rollo a Thorin y a los demás: Marcháis, y continuais con vuestra <b>esperada aventura</b>.<br>",
    escena5:"Gandalf ha marchado. Ha escuchado rumores sobre que un poderoso nigromante ha despertado en algún lugar no muy lejano de Rivendell, pero ha decidido marchar e investigar por su propia cuenta. Tú: Bilbo, junto a los enanos, decidís continuar vuestra aventura. Habéis de avanzar tras las montañas, pero ya oscurece. Las nubes comienzan a invadir el firmamento, y os veis casi completamente privados de la luz natural que la luna os estaba brindando hasta aquel momento. Mientras cruzais por un estrecho y tortuoso camino que rodea la montaña, sentís como no tan solo el suelo tiembla, sino el cómo todo a vuestro alrededor deja de tener sentido: El suelo se mueve, las paredes despiertan y el cielo truena mientras comienza a llover: Un descomunal elemental de piedra despierta de la montaña, y el suelo se abre a tus pies: Tu camino se separa del de los enanos al caer al vacío, recibiendo varios golpes durante el descenso. <b>Pierdes una cantidad aleatoria de vidas</b>.<br>",
    escena6:"Todo te da vueltas. Casi has perdido el conocimiento y notas como un cálido líquido recorre tu rostro al salirte de una herida de sobre tu cabeza. Al levantarte del suelo, notas algo bajo tu mano: Un anillo. Tan pronto como lo tocas, tienes la imperiosa necesidad de protegerlo a toda costa, así que te lo guardas en el bolsillo. <b>Bilbo añade a su inventario El anillo único</b>. Al erguirte sobre el suelo, ves que hay una criatura justo delante de ti: Gollum. Tragas saliva, y a causa de su comportamiento, sabes que es el dueño de ese precioso anillo del que no te quieres deshacer ni aunque te pagasen con todo el pan de lembas del mundo.<br> ",
    escena61:"No sabes si Gollum está enfadado, confuso o triste. Mira con desconsuelo a todo a su alrededor, buscando un anillo que ya ni siquiera tiene. Te mira, frunce el ceño y gruñe: Está a punto de lanzarte otra pregunta.<br>",
    escena62:"Observas como cada vez que das una respuesta, sea errónea o correcta, Gollum pierde mas el norte. Sube y baja, salta y casi baila, mirando hasta debajo de las piedras y atrapando un pescado para abrirle la boca y buscar un anillo entre sus labios. Vuelve a mirarte, tira el pescado y se prepara para realizar otra pregunta.<br>",
    escena63:"Gollum grita y pierde su concentración. Da saltos, vueltas y se golpea la cabeza. ¿Dónde está su preciado anillo? Te mira como si observase a la cosa más inmunda del planeta y enseña sus dientes podridos cubiertos de restos de pescado. ¡Bah! Te da la espalda y se pone a levantar piedras, buscando el anillo. Tú decides aprovechar la oportunidad para correr y escapar del lugar, con ese precioso anillo en tu bolsillo.",
    escena7:"Escapas de la cueva y te reunes con elf resto de la compañía. Absolutamente todos ellos se alegran de verte, y aunque ellos tienen tantas heridas de guerra como tú, no dudan ni un solo segundo sobre que abrazarte es la manera correcta de recibirte. Aun así, Thorin y Dwallin siguen siendo reservados a tu alrededor. No logras ganarte su respeto por completo. Pero parece que no tenéis descanso alguno: cuando os alejáis de la montaña, escucháis un gutural rugido. No es un huargo, ni un orco, o... ¿Lo era? <br><br> Azog el profanador emerge de entre las sombras a lomos de un lobo albino gigante. Thorin siente un escalofrío recorrer su espalda, recordando el cómo su padre murió tiempo atrás. Pero son demasiados orcos, un escuadrón, así que tratáis de escapar cuanto antes. <br>",
    ending:"<b><span>¡ENHORABUENA!</span></b><br><br> Has completado la historia. Has llegado hasta el final, y has tomado las decisiones correctas suficientes como para ganarte un <b>pan de lembas</b> virtual.<br><br>Pero tu historia no acaba aquí. El objetivo de los enanos es llegar hasta su antiguo hogar, y recuperar la joya de la corona para recuperar el control de éste, pero... <b>Te esperan caminos tortuosos, y enemios que dejarían en vergüenza a aquellos que te has encontrado hasta ahora</b>.<br><br><b>CONTINUARÁ...</b><br>"
  };

